language: csharp
mono: none
dotnet: 2.1.4
script:
  - dotnet build System.IO.Abstractions --framework netstandard1.4
  - dotnet build TestingHelpers --framework netstandard1.4
  - dotnet test TestHelpers.Tests --framework netcoreapp2.0
