version: 2.1.0.{build}

image: Visual Studio 2017
configuration: Release

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true
  
init:
  ps: |-
    $env:ASSEMBLY_VERSION = "2.0.0.0"
    $env:PACKAGE_VERSION = "2.1.0"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: $(ASSEMBLY_VERSION)
  package_version: $(PACKAGE_VERSION)

before_build:
  cmd: nuget restore

build:
  publish_nuget: true
  
deploy:
- provider: NuGet
  api_key:
    secure: lUmSV95QwsQtvPkHT02PT5fswmVcW0oMIJvOGEincUNnUNtTe3DOIjVEOpC0CMkQ
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
