image:
  - Visual Studio 2019
  - Visual Studio 2019 Preview
  - Ubuntu

configuration: Release

# Don't start CI for branches that already have a PR
skip_branch_with_pr: true

# Don't start CI when tags are pushed
skip_tags: true

# Limit CI to master branch (and PRs targeting it)
branches:
  only:
    - master

# Publish NuGet packages and symbols
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true

# Perform deployments only for Windows job
for:
  - matrix:
      only:
        - image: Visual Studio 2019
    deploy:
      - provider: NuGet
        api_key:
          secure: dZ2lowWe8KkDiUSXgKS/SulxjuKVSN6t7Jfzfx6co664SRxoXnX+3nsVpYZAJtla
        skip_symbols: false
        artifact: /.*\.nupkg/
        on:
          branch: master

      - provider: GitHub
        tag: v$(appveyor_build_version)
        prerelease: false
        artifact: /.*\.nupkg/
        auth_token:
          secure: Rrk1zp93EpCyxec/GXKnRnJjX7vU+ClNZEBnxbM+1j6l+C56qSV7B/fUrVsJuZYV
        on:
          branch: master
