image: Visual Studio 2017
configuration: Release

skip_branch_with_pr: true
branches:
  only:
    - master

version: 2.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

install
# Temporarily install InheritDoc
- nuget install inheritdoc -Version 1.2.0.1

before_build:
- nuget restore

build:
  publish_nuget: true

before_package:
# This step replaces the inheritdoc tags in the xml documentation with documentation from mscorlib.xml
- ps: inheritdoc\1.2.0.1\tools\InheritDoc.exe -b $env:APPVEYOR_BUILD_FOLDER -g '\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml' -o

deploy:
- provider: NuGet
  api_key:
    secure: lUmSV95QwsQtvPkHT02PT5fswmVcW0oMIJvOGEincUNnUNtTe3DOIjVEOpC0CMkQ
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
