image: Visual Studio 2017
configuration: Release

skip_branch_with_pr: true
branches:
  only:
    - master

version: 2.1.0.{build}

pull_requests:
  do_not_increment_build_number: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

environment:
  INHERITDOC_VERSION: "1.2.2.1"
  TEMP_DIR: c:/temp

install:
# Temporarily install InheritDoc using the NuGet CLI
- nuget install inheritdoc -Version %INHERITDOC_VERSION% -OutputDirectory %TEMP_DIR%

before_build:
- nuget restore

build:
  publish_nuget: true

before_package:
# This step replaces the inheritdoc tags in the xml documentation with documentation from mscorlib.xml
- ps: %TEMP_DIR%\InheritDoc.%INHERITDOC_VERSION%\tools\InheritDoc.exe -b $env:APPVEYOR_BUILD_FOLDER -g 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.X\mscorlib.xml' -o

deploy:
- provider: NuGet
  api_key:
    secure: lUmSV95QwsQtvPkHT02PT5fswmVcW0oMIJvOGEincUNnUNtTe3DOIjVEOpC0CMkQ
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master
